### PR TITLE
Cleanup/environment

### PR DESCRIPTION
**Pull request by sparkcode-io**
What does this PR do?
- Removes hardcoded config values from Microservices and loads config from environment instead (each Microservice will fallback to .env files like before if variables can't be found in docker environment)
- Adds some type safety to env values so we can know if values are missing or not needed 
- Adds new scripts for development and production builds 

In order to run docker we need to specify a config file so that our env variables are loaded. I added this info to the readme as well. 

Build: 
docker-compose --env-file config-example/.env.dev build

Run: 
docker-compose --env-file config-example/.env.dev up

Real config files will be stored in a secure location and not checked into source control

### CODE REVIEW

**Comment by JarethRader** [comment]
Everything looks fine, except it looks like for some reason under /API/Whiteboard/src/data-access/utils, there are a few json (tileSet.json, front.json, and back.json) files that disappeared from that folder that the server uses for the initial postgreSQL table setup. Without them, trying to run docker failed for me; it only looks like the whiteboard service is failing to start.

Otherwise it looks like everything else starts up fine.

**Comment by sparkcode-io** [comment]
> Everything looks fine, except it looks like for some reason under /API/Whiteboard/src/data-access/utils, there are a few json (tileSet.json, front.json, and back.json) files that disappeared from that folder that the server uses for the initial postgreSQL table setup. Without them, trying to run docker failed for me; it only looks like the whiteboard service is failing to start.
> 
> Otherwise it looks like everything else starts up fine.

Hmm, yeah I moved those files out of the src folder and into a config folder. This was because the json files don't get compiled by typescript into the dist folder which would cause the build to fail in production. 

The code appears to be referencing the correct paths so I'm unsure why this would fail. I'll try to pull a fresh copy of the repo to verify it's working.

**Comment by JarethRader** [comment]
Worst case scenario, we don't necessarily need to compile with typescript. Some people like to reduce the file size of their code when we then put it on a server by compiling and minifying everything with webpack, but it's mostly up to personal preference.

**Review by JarethRader — COMMENTED** [review]
Everything is working locally and it should be set for an initial deployment.

**Pull request merged**
